### ISSUE TITLE
More OOP less Classy

### ISSUE THREAD

**Issue by trans** [seamusabshere/string_enumerator#1]
There seems to be a bug going around, build API's in the Class clouds. Bring her down to earth:

```
se = StringEnumerator.new(string)
se.enumerate(replacements_hash)
```

btw doesn't sprintf have some sort to naming technique?

**Comment by seamusabshere** [comment]
Trans,

Thanks for your comments. Here's what I'm thinking:

1) In my application, I use a single StringEnumerator subclass instance to enumerate a whole bunch of strings with same exact replacements. It didn't occur to me to create a new StringEnumerator object for each string. For example:

```
a = FooEnumerator.new
strs.each do |str|
  puts a.enumerate str
end
```

I think you're proposing

```
replacements = { ... }
strs.each do |str|
  puts StringEnumerator.new(replacements).enumerate(str)
end
```

2) This is meant to be used for multiple possibilities per placeholder:

  colors = red, blue
  tastes = savory, sweet
  string = My favorite color is [color] and my favorite taste is [taste]

  =>

  My favorite color is red and my favorite taste is savory
  My favorite color is red and my favorite taste is sweet
  My favorite color is blue and my favorite taste is savory
  My favorite color is blue and my favorite taste is sweet

I might be able to rewrite the inner loop with <code>sprintf</code> and named replacements, but it may make the "recursion" more complicated.

Best and thanks again for your comments,
Seamus

**Comment by trans** [comment]
I see so you are doing the opposite. Ok. That's fine too. Just turn it arround:

```
se = StringEnumerator.new(replacements_hash)
se.enumerate(string)
```

My point is really that it's over kill to have to define a new class to accomplish this. A developer can always use delegation to create a Class if one is needed:

```
class MyStringEnumerator
   def replacements
     ...
   end

   def enumerate(string)
     se = StringEnumerator.new(replacements)
     se.enumerate(string)
   end
end
```

Its' a good OOP general principle: "Delegation is your friend." :-)

**Comment by seamusabshere** [comment]
Yah, I like it better your way:

https://github.com/seamusabshere/string_enumerator/commit/5d347bc2ad2a1cc0fa35c9ea45d2e3ac2820c767

**Comment by trans** [comment]
Awesome! When you feel your code is solid be sure to post about it on Ruby Flow (http://www.rubyflow.com/).
